name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-sbt-libs
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier/v1
        key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
